### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by dannyb648** [mattdavis90/node-tado-client#16]
Really like the module, thanks for all the work so far!

Currently using this in a Typescript project, so adding in some type declarations would be really useful.

Happy to do this in a PR if you aren't planning on doing it! Love to get involved

**Comment by mattdavis90** [comment]
Hi Danny, Apologies for taking my time. I have briefly used Typescript in other projects but have no plans to support it in this library. If you'd like to add Typescript declarations then I'm more than happy to accept this as a pull request. It would be great to have more contributions. Is there a way to add the types without breaking Javascript support?

**Comment by mattdavis90** [comment]
Would it be done using ```.d.ts``` files as described [here](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html)?
