### ISSUE TITLE
Country needed as param in tado.getEnergyIQ(home_id);

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#31]
Calling getEnergyIQ fails,

[log] 2022-12-25 13:18:20 getEnergyIQ() 400 Bad Request
[log] 2022-12-25 13:18:20 getEnergyIQ() { message: 'Missing required request parameters: [country]' }

need to add country as parm on the API request.

**Comment by mattdavis90** [comment]
Hi, did this break recently? It isn't a feature I tend to use to be honest so don't regularly test it.

**Comment by mattdavis90** [comment]
The EnergyIQ API calls aren't available in the web interface so I'm not 100% sure how they were found (I didn't reverse engineer them) so I'm not exactly sure how to modify the call.

**Comment by dudz40** [comment]
Yes it did a few weeks back, had the same with my call. Was implementing
your API and same thing happened.

Thanks 🙏 for the nice work you folks are putting into this.


Martin Verbeek

Op zo 25 dec. 2022 14:37 schreef Matt Davis ***@***.***>:

**Comment by dudz40** [comment]
this works 

const uri = `https://energy-insights.tado.com/api/homes/${this.homeId}/consumption?country=${this.countryCode}`;

**Comment by mattdavis90** [comment]
That's what I just tried as well and noticed it works. I've pushed a new version. About to do the release

**Comment by dudz40** [comment]
maybe another suggestion I implemented myself... Add the homeId to the private vars, and set it when calling getMe, that way homeId is not mandatory anymore in most calls.

**Comment by mattdavis90** [comment]
I guess I could do that. I'm not sure if it is possible to have multiple homes but the getMe call returns an array so I'm assuming that it is possible. Because my primary goal for the library is NodeRed integration I'm happy leaving as is. I guess I could make it optional and do a `getMe` and assume first home if it were an issue. Happy to add it if there is interest.

**Comment by dudz40** [comment]
not in there, no way to add that in the App or Webapp. or at least i cannot find how to. I have two tado id's (bridges)  and with two Tado instances it works like a charm with multiple homeId's.
