### ISSUE TITLE
Enhancement request: method setTimeTable

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#32]
Is it possible to add setTimeTable? I use it to set a saved schedule with getTimeTable (or part of it).  Below modified part of what I use now..

`	async setTimeTable(id, block, schedule, dayType)
	const uri = `https://my.tado.com/api/v2/homes/${this.homeId}/zones/${id}/schedule/timetables/${block}/blocks/${dayType}`;
			const response = await axios.put(uri, schedule);`

dayType is list below.
['MONDAY_TO_SUNDAY', 'MONDAY_TO_FRIDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']

**Comment by mattdavis90** [comment]
I'm happy to add that. Do you have a PR for this? Did you say you have a fork of the library? I'm wondering if it is worth combining features?

**Comment by dudz40** [comment]
No fork. I had a TadoClient module that is part of my app, it contains some specific methods as well, but this is a generic method that was missing in your implementation.

**Comment by mattdavis90** [comment]
This is now available on the master branch - appreciate if you could test the implementation. My testing seemed to work

**Comment by dudz40** [comment]
Tested and confirmed working.
