### ISSUE TITLE
fanLevel usage in overlays?

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#33]
I am not getting the fanLevel. I normally use fanSpeed in the setting overlay for AUTO, LOW, MIDDLE and HIGH. 
FanLevel is throwing 422 on these values.

**Comment by mattdavis90** [comment]
Hi, I don't own an air con unit so I'm not sure what the values should be. I know they got changed at some point because there have been PRs and issue raised. If you think there's an issue though and you can test it then I'm happy to accept PRs. The air con stuff I try not to touch too much because I can't test it.

**Comment by dudz40** [comment]
I own a couple of them and it might be that newer ones are using fanLevel, mine are using definitly fanSpeed. Below the setting that is returned from my AC, solution might be simple, just add fanSpeed to the properties it tests on ;-), units that support fanLevel are good and fanSpeed as well.

"setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"HEAT","temperature":{"celsius":19,"fahrenheit":66.2},"fanSpeed":"AUTO"}

**Comment by dudz40** [comment]
looks like its usrACcapabilities are found under control of the AC. Will close this issue. Would be grateful though if you could add fanSpeed property to the setZoneOverlays method, this allows me to go on with the move to your library.
I am waiting on a v3+ AC device to replace one of my V2 AC devices and check further.

**Comment by mattdavis90** [comment]
I've pushed a change to master that hopefully fixes this for you and remains backward compatible. Are you able to test?

**Comment by dudz40** [comment]
Hi Matt, will test it later today, in the middle of some changes as well.

Thanks a mill, will let you know asap.

Martin Verbeek

Op do 29 dec. 2022 13:51 schreef Matt Davis ***@***.***>:

**Comment by dudz40** [comment]
Works!. Was a bit puzzled first, as i though i could use fanSpeed in the overlay, but it has to be fanLevel.

**Comment by mattdavis90** [comment]
Sorry, yes I wanted to maintain backward compatibility so didn't change and parameter names just in case.
