### ISSUE TITLE
EnerqyIQ update/getTariff uses wrong endpoint

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#34]
the endpoint of the getTariff should be tariffs not tariff. The PUT operation should have an ID of the updating tariff entry as well. Not sure if you are retrieving that somehow.

**Comment by mattdavis90** [comment]
I can add the 's' on to the end of those URLs. Do you have an example where the ID should go? Again, this isn't an API call that I use. Thanks

**Comment by dudz40** [comment]
Just stumbled across it when i wanted to update/add a tariff. I saw your comment in the code it was not working.

https://energy-insights.tado.com/api/homes/homeid/tariffs/**b8b6ee53-8285-4493-9668-7a5f0ee13**

this bold is the id on the PUT request.

**Comment by mattdavis90** [comment]
Awesome. I'll update now. Thanks

**Comment by mattdavis90** [comment]
Should be on master now

**Comment by mattdavis90** [comment]
This is now in release v0.12.2
