### ISSUE TITLE
ZoneDayReport not using arrays for data points

### ISSUE THREAD

**Issue by nistei** [mattdavis90/node-tado-client#36]
The `dataIntervals` and `dataPoints` are not returned as arrays but should be. Only the type `MeasureBoolean` is implemented correctly.

**Comment by mattdavis90** [comment]
Hi, do you have an example JSON blob so that I can update the typing? Equally I'm happy to accept a PR. Thanks

**Comment by mattdavis90** [comment]
This is now released in v0.12.2

**Comment by nistei** [comment]
Working now. Thanks for the quick release.

**Comment by mattdavis90** [comment]
No problem
