### ISSUE TITLE
fan speed not allowed in mode HEAT/COOL

### ISSUE THREAD

**Issue by Aymkdn** [mattdavis90/node-tado-client#41]
Hello,

Thanks for this library.

It used to work very well, but it doesn't anymore… When I send the below command to my AC:
```js
{
  power: 'ON',
  temperature: { celsius: 26 },
  mode: 'COOL', // or 'HEAT'
  fanLevel: 'AUTO',
  zone_id: 2
}
```

I receive an error code 422 with the message: 
```js
{
    code: 'setting.notSupported',
    title: 'fan speed not allowed in mode COOL' // or 'in mode HEAT'
}
```

If I try `fanLevel:"LEVEL2"` (instead of `AUTO`) I receive the below error:
```js
{
    code: 'typeMismatch',
    title: 'Invalid value for property overlays.0.overlay.setting.fanSpeed'
}
```

If I do not provide `fanLevel` I receive the below error:
```js
{
    code: 'typeMismatch',
    title: 'fan level not in supported fan levels [AUTO, LEVEL4, SILENT, LEVEL2, LEVEL3, LEVEL1]'
}
```

If I check the capabilities of the AC with `getZoneCapabilities` I receive the below:
```js
{
  "type": "AIR_CONDITIONING",
  "DRY": {
    "fanLevel": [
      "LEVEL3",
      "LEVEL1",
      "LEVEL4",
      "LEVEL2",
      "AUTO",
      "SILENT"
    ],
    "verticalSwing": [
      "ON",
      "MID",
      "AUTO",
      "UP",
      "DOWN",
      "MID_UP",
      "MID_DOWN"
    ],
    "horizontalSwing": [
      "RIGHT",
      "MID",
      "LEFT",
      "MID_RIGHT",
      "ON",
      "MID_LEFT"
    ]
  },
  "AUTO": {
    "temperatures": {
      "celsius": {
        "min": 16,
        "max": 31,
        "step": 1
      },
      "fahrenheit": {
        "min": 61,
        "max": 88,
        "step": 1
      }
    },
    "fanLevel": [
      "LEVEL3",
      "LEVEL1",
      "LEVEL4",
      "LEVEL2",
      "AUTO",
      "SILENT"
    ],
    "verticalSwing": [
      "ON",
      "MID",
      "AUTO",
      "UP",
      "DOWN",
      "MID_UP",
      "MID_DOWN"
    ],
    "horizontalSwing": [
      "RIGHT",
      "MID",
      "LEFT",
      "MID_RIGHT",
      "ON",
      "MID_LEFT"
    ]
  },
  "HEAT": {
    "temperatures": {
      "celsius": {
        "min": 16,
        "max": 31,
        "step": 1
      },
      "fahrenheit": {
        "min": 61,
        "max": 88,
        "step": 1
      }
    },
    "fanLevel": [
      "LEVEL3",
      "LEVEL1",
      "LEVEL4",
      "LEVEL2",
      "AUTO",
      "SILENT"
    ],
    "verticalSwing": [
      "ON",
      "MID",
      "AUTO",
      "UP",
      "DOWN",
      "MID_UP",
      "MID_DOWN"
    ],
    "horizontalSwing": [
      "RIGHT",
      "MID",
      "LEFT",
      "MID_RIGHT",
      "ON",
      "MID_LEFT"
    ]
  },
  "COOL": {
    "temperatures": {
      "celsius": {
        "min": 16,
        "max": 31,
        "step": 1
      },
      "fahrenheit": {
        "min": 61,
        "max": 88,
        "step": 1
      }
    },
    "fanLevel": [
      "LEVEL3",
      "LEVEL1",
      "LEVEL4",
      "LEVEL2",
      "AUTO",
      "SILENT"
    ],
    "verticalSwing": [
      "ON",
      "MID",
      "AUTO",
      "UP",
      "DOWN",
      "MID_UP",
      "MID_DOWN"
    ],
    "horizontalSwing": [
      "RIGHT",
      "MID",
      "LEFT",
      "MID_RIGHT",
      "ON",
      "MID_LEFT"
    ]
  },
  "FAN": {
    "fanLevel": [
      "LEVEL3",
      "LEVEL1",
      "LEVEL4",
      "LEVEL2",
      "AUTO",
      "SILENT"
    ],
    "verticalSwing": [
      "ON",
      "MID",
      "AUTO",
      "UP",
      "DOWN",
      "MID_UP",
      "MID_DOWN"
    ],
    "horizontalSwing": [
      "RIGHT",
      "MID",
      "LEFT",
      "MID_RIGHT",
      "ON",
      "MID_LEFT"
    ]
  },
  "initialStates": {
    "mode": "COOL",
    "modes": {
      "COOL": {
        "temperature": {
          "celsius": 24,
          "fahrenheit": 75
        },
        "fanLevel": "LEVEL2",
        "verticalSwing": "AUTO",
        "horizontalSwing": "ON"
      },
      "HEAT": {
        "temperature": {
          "celsius": 24,
          "fahrenheit": 75
        },
        "fanLevel": "LEVEL2",
        "verticalSwing": "AUTO",
        "horizontalSwing": "ON"
      },
      "DRY": {
        "fanLevel": "LEVEL2",
        "verticalSwing": "AUTO",
        "horizontalSwing": "ON"
      },
      "FAN": {
        "fanLevel": "LEVEL2",
        "verticalSwing": "AUTO",
        "horizontalSwing": "ON"
      },
      "AUTO": {
        "temperature": {
          "celsius": 24,
          "fahrenheit": 75
        },
        "fanLevel": "LEVEL2",
        "verticalSwing": "AUTO",
        "horizontalSwing": "ON"
      }
    }
  }
}
```

Am I doing something wrong, or Tado changed something?

**Comment by mattdavis90** [comment]
Hi, thanks for getting in touch. I don't own a Tado AC so I'm not able to test those API calls, in the past I've worked with others to help out. I can't see anything immediately wrong and the Tado responses indicate you're sending the correct values.

When reverse engineering the rest of the library I have made extensive use of the Tado web app and Chrome's DevTools to watch the network traffic. If you can set an overlay on the web app and see the parameters it sends and to which endpoint then we may be able to replicate it.

Thanks

**Comment by Aymkdn** [comment]
I ended with manually sending the command using Axios:
```js
axios.put('https://my.tado.com/api/v2/homes/HOME_ID/zones/ZONE_ID/overlay?ngsw-bypass=true', {
     "setting": {
       "power": "ON",
       "temperature": {
           "celsius": 26
        },
        "mode": "COOL",
        "fanLevel": "AUTO"
      },
     "termination": {
       "durationInSeconds": 1800,
       "typeSkillBasedApp": "TIMER"
     }
   }, {
   headers: {
     Authorization: 'Bearer ' + tado._accessToken.token.access_token,
   }
});
```

I'm wondering if somewhere in your code you don't change the `fanLevel` to put something else, or if you add something to the parameters?

**Comment by mattdavis90** [comment]
Hi, I've been having a look into this and it looks as though the function goes and gets the zoneState before updating any overlays - it then tries to determine if it should use `fanSpeed` or `fanLevel` - I think this logic is going wrong.

@Aymkdn Are you able to post the output of `await this.getZoneState(home_id, zone_id)` that should help work out what's going wrong.

@dudz40 I've updated the enums on a branch and they'll go in the next release once we've solved the fanLevel issue

**Comment by dudz40** [comment]
"tadoMode": "HOME",
    "geolocationOverride": false,
    "geolocationOverrideDisableTime": null,
    "preparation": null,
    "setting": {
        "type": "AIR_CONDITIONING",
        "power": "ON",
        "mode": "COOL",
        "temperature": {
            "celsius": 20,
            "fahrenheit": 68
        },
        "fanLevel": "SILENT",
        "verticalSwing": "AUTO",
        "horizontalSwing": "MID_RIGHT"
    },
    "overlayType": "MANUAL",
    "overlay": {
        "type": "MANUAL",
        "setting": {
            "type": "AIR_CONDITIONING",
            "power": "ON",
            "mode": "COOL",
            "temperature": {
                "celsius": 20,
                "fahrenheit": 68
            },
            "fanLevel": "SILENT",
            "verticalSwing": "AUTO",
            "horizontalSwing": "MID_RIGHT"
        },
        "termination": {
            "type": "TIMER",
            "typeSkillBasedApp": "NEXT_TIME_BLOCK",
            "durationInSeconds": 1800,
            "expiry": "2023-08-18T22:15:00Z",
            "remainingTimeInSeconds": 3880,
            "projectedExpiry": "2023-08-18T22:15:00Z"
        }
    },
    "openWindow": null,
    "nextScheduleChange": null,
    "nextTimeBlock": {
        "start": "2023-08-18T22:15:00.000Z"
    },
    "link": {
        "state": "ONLINE"
    },
    "activityDataPoints": {
        "acPower": {
            "timestamp": "2023-08-15T14:23:48.807Z",
            "type": "POWER",
            "value": "ON"
        }
    },
    "sensorDataPoints": {
        "insideTemperature": {
            "celsius": 21.98,
            "fahrenheit": 71.56,
            "timestamp": "2023-08-18T21:08:48.626Z",
            "type": "TEMPERATURE",
            "precision": {
                "celsius": 0.1,
                "fahrenheit": 0.1
            }
        },
        "humidity": {
            "type": "PERCENTAGE",
            "percentage": 53.8,
            "timestamp": "2023-08-18T21:08:48.626Z"
        }
    }
}

**Comment by dudz40** [comment]
Not sure, but it looks like if the AC is ON, the commands succeed, but when it is OFF they fail with a 422

**Comment by mattdavis90** [comment]
Thanks for the info. That would make sense I think. The code checks the current setting and if out includes fanLevel then sets it, if it doesn't (which sounds like the OFF case) then it sets fanSpeed. I'll have a go tomorrow at updating the code to use the getCapability endpoint as that should indicate fanLevel constantly. Thanks

**Comment by Aymkdn** [comment]
Thanks guys. Let me know if you need anything else from me!

**Comment by mattdavis90** [comment]
I'm hoping the changes on the various-updates branch should help. Are you able to test?

**Comment by Aymkdn** [comment]
> I'm hoping the changes on the various-updates branch should help. Are you able to test?

I did a quick test, and it seems working! Thank you

**Comment by mattdavis90** [comment]
Great, I'll create a release and let you know when it is on npm. Do you use it is nodered and need that library updating as well?

**Comment by Aymkdn** [comment]
I don't use nodeRed, so publishing it to NPM will be sufficient for me.

**Comment by mattdavis90** [comment]
v0.13.0 has been release on npm now

**Comment by Aymkdn** [comment]
thank you!

**Comment by dudz40** [comment]
Thanks Matt, appreciated!

Martin Verbeek

Op za 19 aug. 2023 12:09 schreef Aymeric ***@***.***>:
