### ISSUE TITLE
 code: 'nullable', 'Property overlays.0.overlay.setting.type is required'

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#42]
Hi Matt, getting this after 0.13.0. it used to be okay without specifying type, now it errors both with and without type specified...

below the overlay, followed by the zonestate
{
  zone_id: 17,
  type: 'AIR_CONDITIONING',
  power: 'ON',
  mode: 'COOL',
  fanLevel: 'SILENT',
  verticalSwing: 'AUTO',
  horizontalSwing: 'MID_RIGHT',
  temperature: { celsius: 23.6 }
} NEXT_TIME_BLOCK
2023-08-19T12:01:10.604Z [err] Westzijde overlayComposeAndExecute error response
2023-08-19T12:01:10.605Z [err] Westzijde overlayComposeAndExecute 422
2023-08-19T12:01:10.605Z [err] Westzijde overlayComposeAndExecute {
  errors: [
    {
      code: 'nullable',
      title: 'Property overlays.0.overlay.setting.type is required'
    }
  ]
}

{
    "tadoMode": "HOME",
    "geolocationOverride": false,
    "geolocationOverrideDisableTime": null,
    "preparation": null,
    "setting": {
        "type": "AIR_CONDITIONING",
        "power": "OFF"
    },
    "overlayType": null,
    "overlay": null,
    "openWindow": null,
    "nextScheduleChange": null,
    "nextTimeBlock": {
        "start": "2023-08-19T20:00:00.000Z"
    },
    "link": {
        "state": "ONLINE"
    },
    "activityDataPoints": {
        "acPower": {
            "timestamp": "2023-08-15T14:23:48.807Z",
            "type": "POWER",
            "value": "OFF"
        }
    },
    "sensorDataPoints": {
        "insideTemperature": {
            "celsius": 23.61,
            "fahrenheit": 74.5,
            "timestamp": "2023-08-19T11:44:23.723Z",
            "type": "TEMPERATURE",
            "precision": {
                "celsius": 0.1,
                "fahrenheit": 0.1
            }
        },
        "humidity": {
            "type": "PERCENTAGE",
            "percentage": 61.8,
            "timestamp": "2023-08-19T11:44:23.723Z"
        }
    }
}

**Comment by mattdavis90** [comment]
Thanks for testing and reporting this. When I patch the `fanLevel` parameter I didn't copy through the type parameter from the capabilities API call - oddly this doesn't seem to be needed on my heating setup. I've added a patch on the `fix-overlay-ac` branch, if you could test it, then I'll release to npm. Thansk

**Comment by dudz40** [comment]
looks good.

**Comment by mattdavis90** [comment]
v0.13.1 is now on npm
