### ISSUE TITLE
Typings for ZoneStates does not match the Tado API

### ISSUE THREAD

**Issue by slcp** [mattdavis90/node-tado-client#49]
When attempting to use this library to inspect the `Zones` and `ZoneStates` in my home I have found the typings for the response shapes to be incorrect. The typings for ZoneStates is currently:

```
export type ZoneStates = {
    zoneStates: ZoneState[]
}
```

However when inspecting the responses from the Tado API it looks like:

```
type ZoneId = string
export type ZoneStates = {
    zoneStates: Record<ZoneId, ZoneState>
}
```

I'm guessing the Tado API has changed the shape of this (though that is quite a breaking change!) if I'm what I'm seeing is correct.

I'm happy to put a small PR to resolve this with the above proposed typings, what do you think?

**Comment by mattdavis90** [comment]
I've just doubled checked my account and I agree. It looks like the issue is when I added the typing. The code I have that uses the API in NodeRed uses `Object.keys(zoneStates)` to grab the `zoneIds` so it looks like I just got it wrong. Happy to accept a PR. Thanks

**Comment by slcp** [comment]
Ok, I'm away now for a couple of weeks but I'll raise one when I get back :)
