### ISSUE TITLE
Code 422 when updating via setDeviceTemperatureOffset

### ISSUE THREAD

**Issue by gautiermorel** [mattdavis90/node-tado-client#52]
Hi,
Occasionally, I encounter a 422 error when attempting to update the temperature offset for a device.
`AxiosError: Request failed with status code 422`

How can I handle this ?
Thanks ! 🙌

**Comment by mattdavis90** [comment]
Hi,

What type of device are you setting an offset on? I have only experienced a 422 with the TRVs if I try to set the value too frequently. The TRVs have a "cool off" period were they re-calibrate - you can hear the motor turning then there is a small pause. I'm not sure if this is your issue.

Are you able to reliably replicate the issue?

Thanks

**Comment by gautiermorel** [comment]
Hi @mattdavis90 - Thanks for you quick answer ! After investigation I might found the root cause. I'm trying to set an offset or more than -11°Celsius on one of my TRV and from the frontend part, It seems we have a limit of setting that offset to maximum -/+10.9°Celsius !

**Comment by gautiermorel** [comment]
I can either close the issue or you want maybe add a custom error in case of offset too high ?

**Comment by mattdavis90** [comment]
No problem. That's interesting to know. I might see if there is a hint to the min/max in one of the other API calls and see if we can provide a better error message. I'll leave this open until I've taken a look. Thanks

**Comment by gautiermorel** [comment]
Yeah, so it seems like +/-9.9 is actually the limit ! (not 11 as I suggested earlier - also make more sense to have value around 10 than 11 as a limit imo 😄)
I'm handling the issue on my side - thanks again for you quick reply ! Have a good one !

**Comment by mattdavis90** [comment]
As far as I can tell from looking at the web app and playing around with the API there isn't an API call for determining the min/max and the web app appears to be hard-coded to +/-10C. If I can't retrieve the value manually then I don't think I'll hard code it in the library just in case a firmware update changes the value at some point. Thanks for raising the query. I hope the library continues to be useful for your needs :)
