### ISSUE TITLE
Code 403 on getEnergyIQ

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#53]
since a couple of days i am getting a 403 on the getEnergyIQ call. Any other reports?

**Comment by mattdavis90** [comment]
No other issues have been raised. There was mention of Tado changing how authentication works but I rolled out an update that should have fixed that. They removed basic Auth from all endpoints and require JWT, which should now be the case for this library as well.

This isn't an API call I personally use, so it is also possible that Tado changed the API call. Are you still able to access the data in the app and web browser? If you can then we should be able to see the new API call in developer tools.

**Comment by mattdavis90** [comment]
I misremembered the JWT and Auth fixes were for AirConfort - https://github.com/mattdavis90/node-tado-client/commit/03e5a81981dd72e31917693924dbe87d8a924f7c

**Comment by dudz40** [comment]
Will have a check as I saw auth related things in the error.

Martin Verbeek

Op do 11 jan 2024 08:50 schreef Matt Davis ***@***.***>:

**Comment by dhavalsalwala** [comment]
I think tado has changed API URL. For me this works via the rest client,

https://energy-insights.tado.com/api/homes/<HOME_ID>/consumptionOverview?month=2024-07&country=IE

**Comment by mattdavis90** [comment]
That looks like a totally different endpoint - probably worth implementing that as well but it doesn't have the same response as the original endpoint. I don't really use the EnergyIQ stuff in Tado so there isn't much data in my account to test with but as far as I can tell there isn't a direct replacement for the older endpoint. I'll look to include the overview endpoint and remove the old function call.

**Comment by mattdavis90** [comment]
This is now pushed up into v0.16.0

**Comment by mattdavis90** [comment]
The API call is `getEnergyIQOverview` and I've removed the broken API call

**Comment by dhavalsalwala** [comment]
Thanks @mattdavis90 . I will test new API.

**Comment by abn** [comment]
@mattdavis90 the `country` parameter is superfluous here. Tested with and and without, getting the same response back. Maybe good to remove the extra api call in the `getEnergyIQOverview` implementation.

**Comment by mattdavis90** [comment]
@abn Happy to remove that. There's no change to the function signature by dong that so doesn't feel like a big change :)

**Comment by abn** [comment]
Done in #76
