### ISSUE TITLE
setDeviceTemperatureOffset typing is incorrect

### ISSUE THREAD

**Issue by quelqundev** [mattdavis90/node-tado-client#54]
The prototyping of setDeviceTemperatureOffset describe serialNo as a number 👍 https://github.com/mattdavis90/node-tado-client/blob/13627883a532285faf7f8fe7d86f661fe1df59b5/build/index.d.ts#L76

...but in the test of API its a string :

See https://github.com/mattdavis90/node-tado-client/blob/13627883a532285faf7f8fe7d86f661fe1df59b5/test/index.test.js#L553

I suggest to correct the `index.d.ts` file

**Comment by mattdavis90** [comment]
Oops. I'm away from my computer at the minute you're welcome to open a PR, or I can correct it when I'm back

**Comment by quelqundev** [comment]
@mattdavis90 PR created with the very tiny little fix. Thanks for all the work done and the reactivity ! 👍 

Could you update the package on NPM please ?

**Comment by mattdavis90** [comment]
Thanks for spotting this and the PR. I've merged and will sort out a release when I'm back at my computer. Annoyingly the git workflow stopped working to release and I haven't fixed it yet.

**Comment by mattdavis90** [comment]
v0.14.1 is no up on npm

**Comment by quelqundev** [comment]
@mattdavis90 i may be wrong but i dont see the fix published in the v0.14.1... :(

**Comment by mattdavis90** [comment]
I shouldn't have done the PR on my phone. I didn't realise that you'd changed the `build/` file and when I rebuilt the release I accidentally removed your changes. I've uploaded a 0.14.2 now because NPM won't let you overwrite versions

**Comment by quelqundev** [comment]
Thanks for your reactivity ! :)
It's fixed !
